Country.create([
                 { enabled: false, id: 1, iso: 'AF', iso3: 'AFG', name: 'AFGHANISTAN', numcode: 4, printable_name: 'Afghanistan' },
                 { enabled: false, id: 2, iso: 'AL', iso3: 'ALB', name: 'ALBANIA', numcode: 8, printable_name: 'Albania' },
                 { enabled: false, id: 3, iso: 'DZ', iso3: 'DZA', name: 'ALGERIA', numcode: 12, printable_name: 'Algeria' },
                 { enabled: false, id: 4, iso: 'AS', iso3: 'ASM', name: 'AMERICAN SAMOA', numcode: 16, printable_name: 'American Samoa' },
                 { enabled: false, id: 5, iso: 'AD', iso3: 'AND', name: 'ANDORRA', numcode: 20, printable_name: 'Andorra' },
                 { enabled: false, id: 6, iso: 'AO', iso3: 'AGO', name: 'ANGOLA', numcode: 24, printable_name: 'Angola' },
                 { enabled: false, id: 7, iso: 'AI', iso3: 'AIA', name: 'ANGUILLA', numcode: 660, printable_name: 'Anguilla' },
                 { enabled: false, id: 8, iso: 'AG', iso3: 'ATG', name: 'ANTIGUA AND BARBUDA', numcode: 28, printable_name: 'Antigua and Barbuda' },
                 { enabled: false, id: 9, iso: 'AR', iso3: 'ARG', name: 'ARGENTINA', numcode: 32, printable_name: 'Argentina' },
                 { enabled: false, id: 10, iso: 'AM', iso3: 'ARM', name: 'ARMENIA', numcode: 51, printable_name: 'Armenia' },
                 { enabled: false, id: 11, iso: 'AW', iso3: 'ABW', name: 'ARUBA', numcode: 533, printable_name: 'Aruba' },
                 { enabled: false, id: 12, iso: 'AU', iso3: 'AUS', name: 'AUSTRALIA', numcode: 36, printable_name: 'Australia' },
                 { enabled: false, id: 13, iso: 'AT', iso3: 'AUT', name: 'AUSTRIA', numcode: 40, printable_name: 'Austria' },
                 { enabled: false, id: 14, iso: 'AZ', iso3: 'AZE', name: 'AZERBAIJAN', numcode: 31, printable_name: 'Azerbaijan' },
                 { enabled: false, id: 15, iso: 'BS', iso3: 'BHS', name: 'BAHAMAS', numcode: 44, printable_name: 'Bahamas' },
                 { enabled: false, id: 16, iso: 'BH', iso3: 'BHR', name: 'BAHRAIN', numcode: 48, printable_name: 'Bahrain' },
                 { enabled: false, id: 17, iso: 'BD', iso3: 'BGD', name: 'BANGLADESH', numcode: 50, printable_name: 'Bangladesh' },
                 { enabled: false, id: 18, iso: 'BB', iso3: 'BRB', name: 'BARBADOS', numcode: 52, printable_name: 'Barbados' },
                 { enabled: false, id: 19, iso: 'BY', iso3: 'BLR', name: 'BELARUS', numcode: 112, printable_name: 'Belarus' },
                 { enabled: false, id: 20, iso: 'BE', iso3: 'BEL', name: 'BELGIUM', numcode: 56, printable_name: 'Belgium' },
                 { enabled: false, id: 21, iso: 'BZ', iso3: 'BLZ', name: 'BELIZE', numcode: 84, printable_name: 'Belize' },
                 { enabled: false, id: 22, iso: 'BJ', iso3: 'BEN', name: 'BENIN', numcode: 204, printable_name: 'Benin' },
                 { enabled: false, id: 23, iso: 'BM', iso3: 'BMU', name: 'BERMUDA', numcode: 60, printable_name: 'Bermuda' },
                 { enabled: false, id: 24, iso: 'BT', iso3: 'BTN', name: 'BHUTAN', numcode: 64, printable_name: 'Bhutan' },
                 { enabled: false, id: 25, iso: 'BO', iso3: 'BOL', name: 'BOLIVIA', numcode: 68, printable_name: 'Bolivia' },
                 { enabled: false, id: 26, iso: 'BA', iso3: 'BIH', name: 'BOSNIA AND HERZEGOVINA', numcode: 70, printable_name: 'Bosnia and Herzegovina' },
                 { enabled: false, id: 27, iso: 'BW', iso3: 'BWA', name: 'BOTSWANA', numcode: 72, printable_name: 'Botswana' },
                 { enabled: false, id: 28, iso: 'BR', iso3: 'BRA', name: 'BRAZIL', numcode: 76, printable_name: 'Brazil' },
                 { enabled: false, id: 29, iso: 'BN', iso3: 'BRN', name: 'BRUNEI DARUSSALAM', numcode: 96, printable_name: 'Brunei Darussalam' },
                 { enabled: false, id: 30, iso: 'BG', iso3: 'BGR', name: 'BULGARIA', numcode: 100, printable_name: 'Bulgaria' },
                 { enabled: false, id: 31, iso: 'BF', iso3: 'BFA', name: 'BURKINA FASO', numcode: 854, printable_name: 'Burkina Faso' },
                 { enabled: false, id: 32, iso: 'BI', iso3: 'BDI', name: 'BURUNDI', numcode: 108, printable_name: 'Burundi' },
                 { enabled: false, id: 33, iso: 'KH', iso3: 'KHM', name: 'CAMBODIA', numcode: 116, printable_name: 'Cambodia' },
                 { enabled: false, id: 34, iso: 'CM', iso3: 'CMR', name: 'CAMEROON', numcode: 120, printable_name: 'Cameroon' },
                 { enabled: false, id: 35, iso: 'CA', iso3: 'CAN', name: 'CANADA', numcode: 124, printable_name: 'Canada' },
                 { enabled: false, id: 36, iso: 'CV', iso3: 'CPV', name: 'CAPE VERDE', numcode: 132, printable_name: 'Cape Verde' },
                 { enabled: false, id: 37, iso: 'KY', iso3: 'CYM', name: 'CAYMAN ISLANDS', numcode: 136, printable_name: 'Cayman Islands' },
                 { enabled: false, id: 38, iso: 'CF', iso3: 'CAF', name: 'CENTRAL AFRICAN REPUBLIC', numcode: 140, printable_name: 'Central African Republic' },
                 { enabled: false, id: 39, iso: 'TD', iso3: 'TCD', name: 'CHAD', numcode: 148, printable_name: 'Chad' },
                 { enabled: false, id: 40, iso: 'CL', iso3: 'CHL', name: 'CHILE', numcode: 152, printable_name: 'Chile' },
                 { enabled: false, id: 41, iso: 'CN', iso3: 'CHN', name: 'CHINA', numcode: 156, printable_name: 'China' },
                 { enabled: false, id: 42, iso: 'CO', iso3: 'COL', name: 'COLOMBIA', numcode: 170, printable_name: 'Colombia' },
                 { enabled: false, id: 43, iso: 'KM', iso3: 'COM', name: 'COMOROS', numcode: 174, printable_name: 'Comoros' },
                 { enabled: false, id: 44, iso: 'CG', iso3: 'COG', name: 'CONGO', numcode: 178, printable_name: 'Congo' },
                 { enabled: false, id: 45, iso: 'CD', iso3: 'COD', name: 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', numcode: 180, printable_name: 'Congo, the Democratic Republic of the' },
                 { enabled: false, id: 46, iso: 'CK', iso3: 'COK', name: 'COOK ISLANDS', numcode: 184, printable_name: 'Cook Islands' },
                 { enabled: false, id: 47, iso: 'CR', iso3: 'CRI', name: 'COSTA RICA', numcode: 188, printable_name: 'Costa Rica' },
                 { enabled: false, id: 48, iso: 'CI', iso3: 'CIV', name: 'COTE D\'IVOIRE', numcode: 384, printable_name: 'Cote D\'Ivoire' },
                 { enabled: false, id: 49, iso: 'HR', iso3: 'HRV', name: 'CROATIA', numcode: 191, printable_name: 'Croatia' },
                 { enabled: false, id: 50, iso: 'CU', iso3: 'CUB', name: 'CUBA', numcode: 192, printable_name: 'Cuba' },
                 { enabled: false, id: 51, iso: 'CY', iso3: 'CYP', name: 'CYPRUS', numcode: 196, printable_name: 'Cyprus' },
                 { enabled: false, id: 52, iso: 'CZ', iso3: 'CZE', name: 'CZECH REPUBLIC', numcode: 203, printable_name: 'Czech Republic' },
                 { enabled: false, id: 53, iso: 'DK', iso3: 'DNK', name: 'DENMARK', numcode: 208, printable_name: 'Denmark' },
                 { enabled: false, id: 54, iso: 'DJ', iso3: 'DJI', name: 'DJIBOUTI', numcode: 262, printable_name: 'Djibouti' },
                 { enabled: false, id: 55, iso: 'DM', iso3: 'DMA', name: 'DOMINICA', numcode: 212, printable_name: 'Dominica' },
                 { enabled: false, id: 56, iso: 'DO', iso3: 'DOM', name: 'DOMINICAN REPUBLIC', numcode: 214, printable_name: 'Dominican Republic' },
                 { enabled: false, id: 57, iso: 'EC', iso3: 'ECU', name: 'ECUADOR', numcode: 218, printable_name: 'Ecuador' },
                 { enabled: false, id: 58, iso: 'EG', iso3: 'EGY', name: 'EGYPT', numcode: 818, printable_name: 'Egypt' },
                 { enabled: false, id: 59, iso: 'SV', iso3: 'SLV', name: 'EL SALVADOR', numcode: 222, printable_name: 'El Salvador' },
                 { enabled: false, id: 60, iso: 'GQ', iso3: 'GNQ', name: 'EQUATORIAL GUINEA', numcode: 226, printable_name: 'Equatorial Guinea' },
                 { enabled: false, id: 61, iso: 'ER', iso3: 'ERI', name: 'ERITREA', numcode: 232, printable_name: 'Eritrea' },
                 { enabled: false, id: 62, iso: 'EE', iso3: 'EST', name: 'ESTONIA', numcode: 233, printable_name: 'Estonia' },
                 { enabled: false, id: 63, iso: 'ET', iso3: 'ETH', name: 'ETHIOPIA', numcode: 231, printable_name: 'Ethiopia' },
                 { enabled: false, id: 64, iso: 'FK', iso3: 'FLK', name: 'FALKLAND ISLANDS (MALVINAS)', numcode: 238, printable_name: 'Falkland Islands (Malvinas)' },
                 { enabled: false, id: 65, iso: 'FO', iso3: 'FRO', name: 'FAROE ISLANDS', numcode: 234, printable_name: 'Faroe Islands' },
                 { enabled: false, id: 66, iso: 'FJ', iso3: 'FJI', name: 'FIJI', numcode: 242, printable_name: 'Fiji' },
                 { enabled: false, id: 67, iso: 'FI', iso3: 'FIN', name: 'FINLAND', numcode: 246, printable_name: 'Finland' },
                 { enabled: false, id: 68, iso: 'FR', iso3: 'FRA', name: 'FRANCE', numcode: 250, printable_name: 'France' },
                 { enabled: false, id: 69, iso: 'GF', iso3: 'GUF', name: 'FRENCH GUIANA', numcode: 254, printable_name: 'French Guiana' },
                 { enabled: false, id: 70, iso: 'PF', iso3: 'PYF', name: 'FRENCH POLYNESIA', numcode: 258, printable_name: 'French Polynesia' },
                 { enabled: false, id: 71, iso: 'GA', iso3: 'GAB', name: 'GABON', numcode: 266, printable_name: 'Gabon' },
                 { enabled: false, id: 72, iso: 'GM', iso3: 'GMB', name: 'GAMBIA', numcode: 270, printable_name: 'Gambia' },
                 { enabled: false, id: 73, iso: 'GE', iso3: 'GEO', name: 'GEORGIA', numcode: 268, printable_name: 'Georgia' },
                 { enabled: false, id: 74, iso: 'DE', iso3: 'DEU', name: 'GERMANY', numcode: 276, printable_name: 'Germany' },
                 { enabled: false, id: 75, iso: 'GH', iso3: 'GHA', name: 'GHANA', numcode: 288, printable_name: 'Ghana' },
                 { enabled: false, id: 76, iso: 'GI', iso3: 'GIB', name: 'GIBRALTAR', numcode: 292, printable_name: 'Gibraltar' },
                 { enabled: false, id: 77, iso: 'GR', iso3: 'GRC', name: 'GREECE', numcode: 300, printable_name: 'Greece' },
                 { enabled: false, id: 78, iso: 'GL', iso3: 'GRL', name: 'GREENLAND', numcode: 304, printable_name: 'Greenland' },
                 { enabled: false, id: 79, iso: 'GD', iso3: 'GRD', name: 'GRENADA', numcode: 308, printable_name: 'Grenada' },
                 { enabled: false, id: 80, iso: 'GP', iso3: 'GLP', name: 'GUADELOUPE', numcode: 312, printable_name: 'Guadeloupe' },
                 { enabled: false, id: 81, iso: 'GU', iso3: 'GUM', name: 'GUAM', numcode: 316, printable_name: 'Guam' },
                 { enabled: false, id: 82, iso: 'GT', iso3: 'GTM', name: 'GUATEMALA', numcode: 320, printable_name: 'Guatemala' },
                 { enabled: false, id: 83, iso: 'GN', iso3: 'GIN', name: 'GUINEA', numcode: 324, printable_name: 'Guinea' },
                 { enabled: false, id: 84, iso: 'GW', iso3: 'GNB', name: 'GUINEA-BISSAU', numcode: 624, printable_name: 'Guinea-Bissau' },
                 { enabled: false, id: 85, iso: 'GY', iso3: 'GUY', name: 'GUYANA', numcode: 328, printable_name: 'Guyana' },
                 { enabled: false, id: 86, iso: 'HT', iso3: 'HTI', name: 'HAITI', numcode: 332, printable_name: 'Haiti' },
                 { enabled: false, id: 87, iso: 'VA', iso3: 'VAT', name: 'HOLY SEE (VATICAN CITY STATE)', numcode: 336, printable_name: 'Holy See (Vatican City State)' },
                 { enabled: false, id: 88, iso: 'HN', iso3: 'HND', name: 'HONDURAS', numcode: 340, printable_name: 'Honduras' },
                 { enabled: true, id: 89, iso: 'HK', iso3: 'HKG', name: 'HONG KONG', numcode: 344, printable_name: 'Hong Kong' },
                 { enabled: false, id: 90, iso: 'HU', iso3: 'HUN', name: 'HUNGARY', numcode: 348, printable_name: 'Hungary' },
                 { enabled: false, id: 91, iso: 'IS', iso3: 'ISL', name: 'ICELAND', numcode: 352, printable_name: 'Iceland' },
                 { enabled: false, id: 92, iso: 'IN', iso3: 'IND', name: 'INDIA', numcode: 356, printable_name: 'India' },
                 { enabled: false, id: 93, iso: 'ID', iso3: 'IDN', name: 'INDONESIA', numcode: 360, printable_name: 'Indonesia' },
                 { enabled: false, id: 94, iso: 'IR', iso3: 'IRN', name: 'IRAN, ISLAMIC REPUBLIC OF', numcode: 364, printable_name: 'Iran, Islamic Republic of' },
                 { enabled: false, id: 95, iso: 'IQ', iso3: 'IRQ', name: 'IRAQ', numcode: 368, printable_name: 'Iraq' },
                 { enabled: false, id: 96, iso: 'IE', iso3: 'IRL', name: 'IRELAND', numcode: 372, printable_name: 'Ireland' },
                 { enabled: false, id: 97, iso: 'IL', iso3: 'ISR', name: 'ISRAEL', numcode: 376, printable_name: 'Israel' },
                 { enabled: false, id: 98, iso: 'IT', iso3: 'ITA', name: 'ITALY', numcode: 380, printable_name: 'Italy' },
                 { enabled: false, id: 99, iso: 'JM', iso3: 'JAM', name: 'JAMAICA', numcode: 388, printable_name: 'Jamaica' },
                 { enabled: false, id: 100, iso: 'JP', iso3: 'JPN', name: 'JAPAN', numcode: 392, printable_name: 'Japan' },
                 { enabled: false, id: 101, iso: 'JO', iso3: 'JOR', name: 'JORDAN', numcode: 400, printable_name: 'Jordan' },
                 { enabled: false, id: 102, iso: 'KZ', iso3: 'KAZ', name: 'KAZAKHSTAN', numcode: 398, printable_name: 'Kazakhstan' },
                 { enabled: false, id: 103, iso: 'KE', iso3: 'KEN', name: 'KENYA', numcode: 404, printable_name: 'Kenya' },
                 { enabled: false, id: 104, iso: 'KI', iso3: 'KIR', name: 'KIRIBATI', numcode: 296, printable_name: 'Kiribati' },
                 { enabled: false, id: 105, iso: 'KP', iso3: 'PRK', name: 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF', numcode: 408, printable_name: 'Korea, Democratic People\'s Republic of' },
                 { enabled: false, id: 106, iso: 'KR', iso3: 'KOR', name: 'KOREA, REPUBLIC OF', numcode: 410, printable_name: 'Korea, Republic of' },
                 { enabled: false, id: 107, iso: 'KW', iso3: 'KWT', name: 'KUWAIT', numcode: 414, printable_name: 'Kuwait' },
                 { enabled: false, id: 108, iso: 'KG', iso3: 'KGZ', name: 'KYRGYZSTAN', numcode: 417, printable_name: 'Kyrgyzstan' },
                 { enabled: false, id: 109, iso: 'LA', iso3: 'LAO', name: 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC', numcode: 418, printable_name: 'Lao People\'s Democratic Republic' },
                 { enabled: false, id: 110, iso: 'LV', iso3: 'LVA', name: 'LATVIA', numcode: 428, printable_name: 'Latvia' },
                 { enabled: false, id: 111, iso: 'LB', iso3: 'LBN', name: 'LEBANON', numcode: 422, printable_name: 'Lebanon' },
                 { enabled: false, id: 112, iso: 'LS', iso3: 'LSO', name: 'LESOTHO', numcode: 426, printable_name: 'Lesotho' },
                 { enabled: false, id: 113, iso: 'LR', iso3: 'LBR', name: 'LIBERIA', numcode: 430, printable_name: 'Liberia' },
                 { enabled: false, id: 114, iso: 'LY', iso3: 'LBY', name: 'LIBYAN ARAB JAMAHIRIYA', numcode: 434, printable_name: 'Libyan Arab Jamahiriya' },
                 { enabled: false, id: 115, iso: 'LI', iso3: 'LIE', name: 'LIECHTENSTEIN', numcode: 438, printable_name: 'Liechtenstein' },
                 { enabled: false, id: 116, iso: 'LT', iso3: 'LTU', name: 'LITHUANIA', numcode: 440, printable_name: 'Lithuania' },
                 { enabled: false, id: 117, iso: 'LU', iso3: 'LUX', name: 'LUXEMBOURG', numcode: 442, printable_name: 'Luxembourg' },
                 { enabled: false, id: 118, iso: 'MO', iso3: 'MAC', name: 'MACAO', numcode: 446, printable_name: 'Macao' },
                 { enabled: false, id: 119, iso: 'MK', iso3: 'MKD', name: 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', numcode: 807, printable_name: 'Macedonia, the Former Yugoslav Republic of' },
                 { enabled: false, id: 120, iso: 'MG', iso3: 'MDG', name: 'MADAGASCAR', numcode: 450, printable_name: 'Madagascar' },
                 { enabled: false, id: 121, iso: 'MW', iso3: 'MWI', name: 'MALAWI', numcode: 454, printable_name: 'Malawi' },
                 { enabled: false, id: 122, iso: 'MY', iso3: 'MYS', name: 'MALAYSIA', numcode: 458, printable_name: 'Malaysia' },
                 { enabled: false, id: 123, iso: 'MV', iso3: 'MDV', name: 'MALDIVES', numcode: 462, printable_name: 'Maldives' },
                 { enabled: false, id: 124, iso: 'ML', iso3: 'MLI', name: 'MALI', numcode: 466, printable_name: 'Mali' },
                 { enabled: false, id: 125, iso: 'MT', iso3: 'MLT', name: 'MALTA', numcode: 470, printable_name: 'Malta' },
                 { enabled: false, id: 126, iso: 'MH', iso3: 'MHL', name: 'MARSHALL ISLANDS', numcode: 584, printable_name: 'Marshall Islands' },
                 { enabled: false, id: 127, iso: 'MQ', iso3: 'MTQ', name: 'MARTINIQUE', numcode: 474, printable_name: 'Martinique' },
                 { enabled: false, id: 128, iso: 'MR', iso3: 'MRT', name: 'MAURITANIA', numcode: 478, printable_name: 'Mauritania' },
                 { enabled: false, id: 129, iso: 'MU', iso3: 'MUS', name: 'MAURITIUS', numcode: 480, printable_name: 'Mauritius' },
                 { enabled: false, id: 130, iso: 'MX', iso3: 'MEX', name: 'MEXICO', numcode: 484, printable_name: 'Mexico' },
                 { enabled: false, id: 131, iso: 'FM', iso3: 'FSM', name: 'MICRONESIA, FEDERATED STATES OF', numcode: 583, printable_name: 'Micronesia, Federated States of' },
                 { enabled: false, id: 132, iso: 'MD', iso3: 'MDA', name: 'MOLDOVA, REPUBLIC OF', numcode: 498, printable_name: 'Moldova, Republic of' },
                 { enabled: false, id: 133, iso: 'MC', iso3: 'MCO', name: 'MONACO', numcode: 492, printable_name: 'Monaco' },
                 { enabled: false, id: 134, iso: 'MN', iso3: 'MNG', name: 'MONGOLIA', numcode: 496, printable_name: 'Mongolia' },
                 { enabled: false, id: 135, iso: 'MS', iso3: 'MSR', name: 'MONTSERRAT', numcode: 500, printable_name: 'Montserrat' },
                 { enabled: false, id: 136, iso: 'MA', iso3: 'MAR', name: 'MOROCCO', numcode: 504, printable_name: 'Morocco' },
                 { enabled: false, id: 137, iso: 'MZ', iso3: 'MOZ', name: 'MOZAMBIQUE', numcode: 508, printable_name: 'Mozambique' },
                 { enabled: false, id: 138, iso: 'MM', iso3: 'MMR', name: 'MYANMAR', numcode: 104, printable_name: 'Myanmar' },
                 { enabled: false, id: 139, iso: 'NA', iso3: 'NAM', name: 'NAMIBIA', numcode: 516, printable_name: 'Namibia' },
                 { enabled: false, id: 140, iso: 'NR', iso3: 'NRU', name: 'NAURU', numcode: 520, printable_name: 'Nauru' },
                 { enabled: false, id: 141, iso: 'NP', iso3: 'NPL', name: 'NEPAL', numcode: 524, printable_name: 'Nepal' },
                 { enabled: false, id: 142, iso: 'NL', iso3: 'NLD', name: 'NETHERLANDS', numcode: 528, printable_name: 'Netherlands' },
                 { enabled: false, id: 143, iso: 'AN', iso3: 'ANT', name: 'NETHERLANDS ANTILLES', numcode: 530, printable_name: 'Netherlands Antilles' },
                 { enabled: false, id: 144, iso: 'NC', iso3: 'NCL', name: 'NEW CALEDONIA', numcode: 540, printable_name: 'New Caledonia' },
                 { enabled: false, id: 145, iso: 'NZ', iso3: 'NZL', name: 'NEW ZEALAND', numcode: 554, printable_name: 'New Zealand' },
                 { enabled: false, id: 146, iso: 'NI', iso3: 'NIC', name: 'NICARAGUA', numcode: 558, printable_name: 'Nicaragua' },
                 { enabled: false, id: 147, iso: 'NE', iso3: 'NER', name: 'NIGER', numcode: 562, printable_name: 'Niger' },
                 { enabled: false, id: 148, iso: 'NG', iso3: 'NGA', name: 'NIGERIA', numcode: 566, printable_name: 'Nigeria' },
                 { enabled: false, id: 149, iso: 'NU', iso3: 'NIU', name: 'NIUE', numcode: 570, printable_name: 'Niue' },
                 { enabled: false, id: 150, iso: 'NF', iso3: 'NFK', name: 'NORFOLK ISLAND', numcode: 574, printable_name: 'Norfolk Island' },
                 { enabled: false, id: 151, iso: 'MP', iso3: 'MNP', name: 'NORTHERN MARIANA ISLANDS', numcode: 580, printable_name: 'Northern Mariana Islands' },
                 { enabled: false, id: 152, iso: 'NO', iso3: 'NOR', name: 'NORWAY', numcode: 578, printable_name: 'Norway' },
                 { enabled: false, id: 153, iso: 'OM', iso3: 'OMN', name: 'OMAN', numcode: 512, printable_name: 'Oman' },
                 { enabled: false, id: 154, iso: 'PK', iso3: 'PAK', name: 'PAKISTAN', numcode: 586, printable_name: 'Pakistan' },
                 { enabled: false, id: 155, iso: 'PW', iso3: 'PLW', name: 'PALAU', numcode: 585, printable_name: 'Palau' },
                 { enabled: false, id: 156, iso: 'PA', iso3: 'PAN', name: 'PANAMA', numcode: 591, printable_name: 'Panama' },
                 { enabled: false, id: 157, iso: 'PG', iso3: 'PNG', name: 'PAPUA NEW GUINEA', numcode: 598, printable_name: 'Papua New Guinea' },
                 { enabled: false, id: 158, iso: 'PY', iso3: 'PRY', name: 'PARAGUAY', numcode: 600, printable_name: 'Paraguay' },
                 { enabled: false, id: 159, iso: 'PE', iso3: 'PER', name: 'PERU', numcode: 604, printable_name: 'Peru' },
                 { enabled: false, id: 160, iso: 'PH', iso3: 'PHL', name: 'PHILIPPINES', numcode: 608, printable_name: 'Philippines' },
                 { enabled: false, id: 161, iso: 'PN', iso3: 'PCN', name: 'PITCAIRN', numcode: 612, printable_name: 'Pitcairn' },
                 { enabled: false, id: 162, iso: 'PL', iso3: 'POL', name: 'POLAND', numcode: 616, printable_name: 'Poland' },
                 { enabled: false, id: 163, iso: 'PT', iso3: 'PRT', name: 'PORTUGAL', numcode: 620, printable_name: 'Portugal' },
                 { enabled: false, id: 164, iso: 'PR', iso3: 'PRI', name: 'PUERTO RICO', numcode: 630, printable_name: 'Puerto Rico' },
                 { enabled: false, id: 165, iso: 'QA', iso3: 'QAT', name: 'QATAR', numcode: 634, printable_name: 'Qatar' },
                 { enabled: false, id: 166, iso: 'RE', iso3: 'REU', name: 'REUNION', numcode: 638, printable_name: 'Reunion' },
                 { enabled: false, id: 167, iso: 'RO', iso3: 'ROM', name: 'ROMANIA', numcode: 642, printable_name: 'Romania' },
                 { enabled: false, id: 168, iso: 'RU', iso3: 'RUS', name: 'RUSSIAN FEDERATION', numcode: 643, printable_name: 'Russian Federation' },
                 { enabled: false, id: 169, iso: 'RW', iso3: 'RWA', name: 'RWANDA', numcode: 646, printable_name: 'Rwanda' },
                 { enabled: false, id: 170, iso: 'SH', iso3: 'SHN', name: 'SAINT HELENA', numcode: 654, printable_name: 'Saint Helena' },
                 { enabled: false, id: 171, iso: 'KN', iso3: 'KNA', name: 'SAINT KITTS AND NEVIS', numcode: 659, printable_name: 'Saint Kitts and Nevis' },
                 { enabled: false, id: 172, iso: 'LC', iso3: 'LCA', name: 'SAINT LUCIA', numcode: 662, printable_name: 'Saint Lucia' },
                 { enabled: false, id: 173, iso: 'PM', iso3: 'SPM', name: 'SAINT PIERRE AND MIQUELON', numcode: 666, printable_name: 'Saint Pierre and Miquelon' },
                 { enabled: false, id: 174, iso: 'VC', iso3: 'VCT', name: 'SAINT VINCENT AND THE GRENADINES', numcode: 670, printable_name: 'Saint Vincent and the Grenadines' },
                 { enabled: false, id: 175, iso: 'WS', iso3: 'WSM', name: 'SAMOA', numcode: 882, printable_name: 'Samoa' },
                 { enabled: false, id: 176, iso: 'SM', iso3: 'SMR', name: 'SAN MARINO', numcode: 674, printable_name: 'San Marino' },
                 { enabled: false, id: 177, iso: 'ST', iso3: 'STP', name: 'SAO TOME AND PRINCIPE', numcode: 678, printable_name: 'Sao Tome and Principe' },
                 { enabled: false, id: 178, iso: 'SA', iso3: 'SAU', name: 'SAUDI ARABIA', numcode: 682, printable_name: 'Saudi Arabia' },
                 { enabled: false, id: 179, iso: 'SN', iso3: 'SEN', name: 'SENEGAL', numcode: 686, printable_name: 'Senegal' },
                 { enabled: false, id: 180, iso: 'SC', iso3: 'SYC', name: 'SEYCHELLES', numcode: 690, printable_name: 'Seychelles' },
                 { enabled: false, id: 181, iso: 'SL', iso3: 'SLE', name: 'SIERRA LEONE', numcode: 694, printable_name: 'Sierra Leone' },
                 { enabled: true, id: 182, iso: 'SG', iso3: 'SGP', name: 'SINGAPORE', numcode: 702, printable_name: 'Singapore' },
                 { enabled: false, id: 183, iso: 'SK', iso3: 'SVK', name: 'SLOVAKIA', numcode: 703, printable_name: 'Slovakia' },
                 { enabled: false, id: 184, iso: 'SI', iso3: 'SVN', name: 'SLOVENIA', numcode: 705, printable_name: 'Slovenia' },
                 { enabled: false, id: 185, iso: 'SB', iso3: 'SLB', name: 'SOLOMON ISLANDS', numcode: 90, printable_name: 'Solomon Islands' },
                 { enabled: false, id: 186, iso: 'SO', iso3: 'SOM', name: 'SOMALIA', numcode: 706, printable_name: 'Somalia' },
                 { enabled: false, id: 187, iso: 'ZA', iso3: 'ZAF', name: 'SOUTH AFRICA', numcode: 710, printable_name: 'South Africa' },
                 { enabled: false, id: 188, iso: 'ES', iso3: 'ESP', name: 'SPAIN', numcode: 724, printable_name: 'Spain' },
                 { enabled: false, id: 189, iso: 'LK', iso3: 'LKA', name: 'SRI LANKA', numcode: 144, printable_name: 'Sri Lanka' },
                 { enabled: false, id: 190, iso: 'SD', iso3: 'SDN', name: 'SUDAN', numcode: 736, printable_name: 'Sudan' },
                 { enabled: false, id: 191, iso: 'SR', iso3: 'SUR', name: 'SURINAME', numcode: 740, printable_name: 'Suriname' },
                 { enabled: false, id: 192, iso: 'SJ', iso3: 'SJM', name: 'SVALBARD AND JAN MAYEN', numcode: 744, printable_name: 'Svalbard and Jan Mayen' },
                 { enabled: false, id: 193, iso: 'SZ', iso3: 'SWZ', name: 'SWAZILAND', numcode: 748, printable_name: 'Swaziland' },
                 { enabled: false, id: 194, iso: 'SE', iso3: 'SWE', name: 'SWEDEN', numcode: 752, printable_name: 'Sweden' },
                 { enabled: false, id: 195, iso: 'CH', iso3: 'CHE', name: 'SWITZERLAND', numcode: 756, printable_name: 'Switzerland' },
                 { enabled: false, id: 196, iso: 'SY', iso3: 'SYR', name: 'SYRIAN ARAB REPUBLIC', numcode: 760, printable_name: 'Syrian Arab Republic' },
                 { enabled: true, id: 197, iso: 'TW', iso3: 'TWN', name: 'TAIWAN, REPUBLIC OF CHINA', numcode: 158, printable_name: 'Taiwan, Republic of China' },
                 { enabled: false, id: 198, iso: 'TJ', iso3: 'TJK', name: 'TAJIKISTAN', numcode: 762, printable_name: 'Tajikistan' },
                 { enabled: false, id: 199, iso: 'TZ', iso3: 'TZA', name: 'TANZANIA, UNITED REPUBLIC OF', numcode: 834, printable_name: 'Tanzania, United Republic of' },
                 { enabled: false, id: 200, iso: 'TH', iso3: 'THA', name: 'THAILAND', numcode: 764, printable_name: 'Thailand' },
                 { enabled: false, id: 201, iso: 'TG', iso3: 'TGO', name: 'TOGO', numcode: 768, printable_name: 'Togo' },
                 { enabled: false, id: 202, iso: 'TK', iso3: 'TKL', name: 'TOKELAU', numcode: 772, printable_name: 'Tokelau' },
                 { enabled: false, id: 203, iso: 'TO', iso3: 'TON', name: 'TONGA', numcode: 776, printable_name: 'Tonga' },
                 { enabled: false, id: 204, iso: 'TT', iso3: 'TTO', name: 'TRINIDAD AND TOBAGO', numcode: 780, printable_name: 'Trinidad and Tobago' },
                 { enabled: false, id: 205, iso: 'TN', iso3: 'TUN', name: 'TUNISIA', numcode: 788, printable_name: 'Tunisia' },
                 { enabled: false, id: 206, iso: 'TR', iso3: 'TUR', name: 'TURKEY', numcode: 792, printable_name: 'Turkey' },
                 { enabled: false, id: 207, iso: 'TM', iso3: 'TKM', name: 'TURKMENISTAN', numcode: 795, printable_name: 'Turkmenistan' },
                 { enabled: false, id: 208, iso: 'TC', iso3: 'TCA', name: 'TURKS AND CAICOS ISLANDS', numcode: 796, printable_name: 'Turks and Caicos Islands' },
                 { enabled: false, id: 209, iso: 'TV', iso3: 'TUV', name: 'TUVALU', numcode: 798, printable_name: 'Tuvalu' },
                 { enabled: false, id: 210, iso: 'UG', iso3: 'UGA', name: 'UGANDA', numcode: 800, printable_name: 'Uganda' },
                 { enabled: false, id: 211, iso: 'UA', iso3: 'UKR', name: 'UKRAINE', numcode: 804, printable_name: 'Ukraine' },
                 { enabled: false, id: 212, iso: 'AE', iso3: 'ARE', name: 'UNITED ARAB EMIRATES', numcode: 784, printable_name: 'United Arab Emirates' },
                 { enabled: false, id: 213, iso: 'GB', iso3: 'GBR', name: 'UNITED KINGDOM', numcode: 826, printable_name: 'United Kingdom' },
                 { enabled: false, id: 214, iso: 'US', iso3: 'USA', name: 'UNITED STATES', numcode: 840, printable_name: 'United States' },
                 { enabled: false, id: 215, iso: 'UY', iso3: 'URY', name: 'URUGUAY', numcode: 858, printable_name: 'Uruguay' },
                 { enabled: false, id: 216, iso: 'UZ', iso3: 'UZB', name: 'UZBEKISTAN', numcode: 860, printable_name: 'Uzbekistan' },
                 { enabled: false, id: 217, iso: 'VU', iso3: 'VUT', name: 'VANUATU', numcode: 548, printable_name: 'Vanuatu' },
                 { enabled: false, id: 218, iso: 'VE', iso3: 'VEN', name: 'VENEZUELA', numcode: 862, printable_name: 'Venezuela' },
                 { enabled: false, id: 219, iso: 'VN', iso3: 'VNM', name: 'VIET NAM', numcode: 704, printable_name: 'Viet Nam' },
                 { enabled: false, id: 220, iso: 'VG', iso3: 'VGB', name: 'VIRGIN ISLANDS, BRITISH', numcode: 92, printable_name: 'Virgin Islands, British' },
                 { enabled: false, id: 221, iso: 'VI', iso3: 'VIR', name: 'VIRGIN ISLANDS, U.S.', numcode: 850, printable_name: 'Virgin Islands, U.s.' },
                 { enabled: false, id: 222, iso: 'WF', iso3: 'WLF', name: 'WALLIS AND FUTUNA', numcode: 876, printable_name: 'Wallis and Futuna' },
                 { enabled: false, id: 223, iso: 'EH', iso3: 'ESH', name: 'WESTERN SAHARA', numcode: 732, printable_name: 'Western Sahara' },
                 { enabled: false, id: 224, iso: 'YE', iso3: 'YEM', name: 'YEMEN', numcode: 887, printable_name: 'Yemen' },
                 { enabled: false, id: 225, iso: 'ZM', iso3: 'ZMB', name: 'ZAMBIA', numcode: 894, printable_name: 'Zambia' },
                 { enabled: false, id: 226, iso: 'ZW', iso3: 'ZWE', name: 'ZIMBABWE', numcode: 716, printable_name: 'Zimbabwe' }
               ])
ActiveRecord::Base.connection.execute('ALTER SEQUENCE countries_id_seq RESTART 227;')
