Skill.create([
               { enabled: true, id: 1, name: 'N/A' },
               { enabled: true, id: 2, name: 'Cooking' },
               { enabled: true, id: 3, name: 'Driving' },
               { enabled: true, id: 4, name: 'Household Chores' },
               { enabled: true, id: 5, name: 'Computer Literate' },
               { enabled: true, id: 6, name: 'HOUSEHOLD CHOIR ' },
               { enabled: true, id: 7, name: 'CARE ELDERLY' },
               { enabled: true, id: 8, name: 'BABY CARE' },
               { enabled: true, id: 9, name: 'BABY CARING' },
               { enabled: true, id: 10, name: 'CLEANING' },
               { enabled: true, id: 11, name: 'COOKNG' },
               { enabled: true, id: 12, name: 'CHILD CARE' },
               { enabled: true, id: 13, name: 'LAUNDRY ' },
               { enabled: true, id: 14, name: 'CHILD CARE BABY CARE' },
               { enabled: true, id: 15, name: 'CARE OF ELDERLY' },
               { enabled: true, id: 16, name: 'ELDERLY CARE' },
               { enabled: true, id: 17, name: 'TAKING CARE,COOKING,IRONING' },
               { enabled: true, id: 18, name: 'TYPING' },
               { enabled: true, id: 19, name: 'BOOK KEEPING' },
               { enabled: true, id: 20, name: 'COOKING,SINGING' },
               { enabled: true, id: 21, name: 'HOUSE HOLD CHOIRS' },
               { enabled: true, id: 22, name: 'CARE GIVING' },
               { enabled: true, id: 23, name: 'TYPING,STENOGRAPHY,CLERICAL WORKS' },
               { enabled: true, id: 24, name: 'HOUSE HOLD BABY CARE ' },
               { enabled: true, id: 25, name: 'ELDERLY CARE HOUSEHOLD CHOIR' },
               { enabled: true, id: 26, name: 'HOUSE HOLD CHOIR' },
               { enabled: true, id: 27, name: 'BABYCARE' },
               { enabled: true, id: 28, name: ' CHILD CARE ' },
               { enabled: true, id: 29, name: 'BABY CARE,COOKING,IRONING' },
               { enabled: true, id: 30, name: 'BABY CARE,CHILD CARE,COOKING,IRONING' },
               { enabled: true, id: 31, name: 'COOKING,BAKING' },
               { enabled: true, id: 32, name: 'COOKING,LAUNDRY' },
               { enabled: true, id: 33, name: 'COOKING.LAUNDRY.IRONING' },
               { enabled: true, id: 34, name: 'COOKIING,LAUNDRY' },
               { enabled: true, id: 35, name: 'COOKING,MANICURE,PEDICURE' },
               { enabled: true, id: 36, name: 'CHILD CARE HOUSEHOLD CHOIR' },
               { enabled: true, id: 37, name: 'HOUSEHOLD' },
               { enabled: true, id: 38, name: 'DISABLED ' },
               { enabled: true, id: 39, name: 'BABY CARE CHILD CARE HOUSEHOLD CHOIR' },
               { enabled: true, id: 40, name: 'BABY CARE. CHILD CARE' },
               { enabled: true, id: 41, name: 'HOUSEHOLD CHOR BABY CARE CARE CHILD CARE' },
               { enabled: true, id: 42, name: 'BABY CARE CHILD CARE' },
               { enabled: true, id: 43, name: 'HOUSEHOLD CHOIR BABY CARE' },
               { enabled: true, id: 44, name: 'CAREGIVING OF DISABLED' },
               { enabled: true, id: 45, name: 'BABY CARE,ELDERLY CARE' },
               { enabled: true, id: 46, name: 'HOUSEHOLD CHOIR BABY CARE CHILD CARE' },
               { enabled: true, id: 47, name: 'MACHINE OPERATOR' },
               { enabled: true, id: 48, name: 'TINTING' },
               { enabled: true, id: 49, name: 'MICROSOFT OFFICE' },
               { enabled: true, id: 50, name: 'EXCEL ;WORD ' },
               { enabled: true, id: 51, name: 'FLUENTLY SPEAK ENGLISH ' },
               { enabled: true, id: 52, name: 'CLEANING DOING HOUSE HOLD ' },
               { enabled: true, id: 53, name: 'TAKING CARE' },
               { enabled: true, id: 54, name: 'OF ANY ALL AGE' },
               { enabled: true, id: 55, name: 'SINGING' },
               { enabled: true, id: 56, name: 'DANCING' },
               { enabled: true, id: 57, name: 'SOFTBALL' },
               { enabled: true, id: 58, name: 'WASHING' },
               { enabled: true, id: 59, name: 'IRONING,AND TAKE CARE OF PETS' },
               { enabled: true, id: 60, name: 'CLEANNG' },
               { enabled: true, id: 61, name: 'IRONING' },
               { enabled: true, id: 62, name: 'GENERAL HOUSWORK' },
               { enabled: true, id: 63, name: 'GENERAL HOUSEWORK' },
               { enabled: true, id: 64, name: 'SEWING' },
               { enabled: true, id: 65, name: 'CLEANNG THE HOUSE' },
               { enabled: true, id: 66, name: 'CLEANING THE HOUSE' },
               { enabled: true, id: 67, name: 'WASHING THE CLOTHES' },
               { enabled: true, id: 68, name: 'IRONING,CLEANING THE HOUSE' },
               { enabled: true, id: 69, name: 'TAKE CARE OF BABIES,ELDERLY' },
               { enabled: true, id: 70, name: 'COOKING,CLEANING' },
               { enabled: true, id: 71, name: 'IRONING,AND TAKE CARE OF BABIES' },
               { enabled: true, id: 72, name: 'ELDERLY ' },
               { enabled: true, id: 73, name: 'GENERAL HOUSEHOLD' },
               { enabled: true, id: 74, name: 'CARE ELDERLY AND COOKING' },
               { enabled: true, id: 75, name: 'FORKCLIFT OPERATOR INJECTION MACHINE' },
               { enabled: true, id: 76, name: 'MOLDING KITCHEN HELPER' },
               { enabled: true, id: 77, name: 'TAKE CARE OF BABIES' },
               { enabled: true, id: 78, name: 'BAKING' },
               { enabled: true, id: 79, name: 'SEWING,DRIVING' },
               { enabled: true, id: 80, name: 'TAKING CARE OF BABIES AND CHILDREN' },
               { enabled: true, id: 81, name: 'SWIMMING' },
               { enabled: true, id: 82, name: 'COOK' },
               { enabled: true, id: 83, name: 'TAKE OF BABIES' },
               { enabled: true, id: 84, name: 'COMPUTER LITERATE AND COOKING' },
               { enabled: true, id: 85, name: 'MEAT CUTTING' },
               { enabled: true, id: 86, name: 'WASHING,CLEANING THE HOUSE' },
               { enabled: true, id: 87, name: 'PAINTER' },
               { enabled: true, id: 88, name: 'SEWER' },
               { enabled: true, id: 89, name: 'CLEANING THE HOUSE,WASHING' },
               { enabled: true, id: 90, name: 'WASHING CLOTHES,' },
               { enabled: true, id: 91, name: 'MIDWIFERY' },
               { enabled: true, id: 92, name: 'CAREGIVING' },
               { enabled: true, id: 93, name: 'DRIVING MOTORCYCLE' },
               { enabled: true, id: 94, name: 'ELECTRICIAN' },
               { enabled: true, id: 95, name: 'COMMUNICATION SKILLS' },
               { enabled: true, id: 96, name: 'DRIVING SKILLS' },
               { enabled: true, id: 97, name: 'AIRCRAFT MAINTENANCE' },
               { enabled: true, id: 98, name: 'HOUSE KEEPING' }
             ])
ActiveRecord::Base.connection.execute('ALTER SEQUENCE skills_id_seq RESTART 99;')
